[project]
name = "thorus-flight"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "cairosvg>=2.8.2",
    "numpy>=2.3.1",
    "py-spy>=0.4.0",
    "pygame>=2.6.1",
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]
