[project]
name = "thorus-flight"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]
